# Generated by Django 5.2.5 on 2025-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='budget',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Standart', 'Standart'), ('Luxury', 'Luxury')], max_length=10),
        ),
    ]
