# Generated by Django 5.2.5 on 2025-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_tripplan_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
