# Generated by Django 5.2.5 on 2025-08-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_tripplan_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplan',
            name='start_date',
        ),
    ]
